name: TFX Addons CI for examples

on:
  push:
    paths:
      - 'tfx_addons/**'
      - 'examples/**'
      - '.github/workflows/ci_examples.yml'
      - 'setup.py'
      - 'pyproject.toml'
    branches:
      - main
      - r*
  pull_request:
    paths:
      - 'tfx_addons/**'
      - 'examples/**'
      - '.github/workflows/ci_examples.yml'
      - 'setup.py'
      - 'pyproject.toml'
    branches:
      - main
      - r*

jobs:
  ci-examples:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        project: [sklearn_penguins, xgboost_penguins]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Cache python environment
      uses: actions/cache@v2
      with:
        # Cache installed dependencies
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirement.txt + project name 
        key: ${{ runner.os }}-pip-ciexamples-${{ matrix.project }}-${{ hashFiles(format('examples/{0}/requirements.txt', matrix.project)) }}
        restore-keys: |
          ${{ runner.os }}-pip-ciexamples-${{ matrix.project }}
          ${{ runner.os }}-pip-ciexamples-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel pytest
        cd examples/${{ matrix.project }}
        pip install -r requirements.txt
    - name: Run tests
      run: |
        cd examples/${{ matrix.project }}
        python -m pytest .
  
